name: demo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  collection: ^1.17.2
  flutter:
    sdk: flutter
  flutter_map: ^6.0.0-dev.3
  flutter_map_query_osm_features:
    path: ../
  latlong2: ^0.9.0

flutter:
  uses-material-design: true
